<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Server Configuration
    |--------------------------------------------------------------------------
    */
    'server' => [
        'name' => env('VURB_SERVER_NAME', env('APP_NAME', 'laravel')),
        'version' => env('VURB_SERVER_VERSION', '1.0.0'),
        'description' => env('VURB_SERVER_DESCRIPTION', 'MCP Server powered by Laravel Vurb'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Internal Token (auto-generated by vurb:install)
    |--------------------------------------------------------------------------
    */
    'internal_token' => env('VURB_INTERNAL_TOKEN'),

    /*
    |--------------------------------------------------------------------------
    | Tool Discovery
    |--------------------------------------------------------------------------
    */
    'tools' => [
        'path' => app_path('Vurb/Tools'),
        'namespace' => 'App\\Vurb\\Tools',
    ],

    /*
    |--------------------------------------------------------------------------
    | Tool Exposition
    |--------------------------------------------------------------------------
    | 'flat' — all tools as top-level MCP tools
    | 'grouped' — tools namespaced by router prefix
    */
    'exposition' => 'flat',

    /*
    |--------------------------------------------------------------------------
    | Transport
    |--------------------------------------------------------------------------
    */
    'transport' => env('VURB_TRANSPORT', 'stdio'),

    /*
    |--------------------------------------------------------------------------
    | Daemon Configuration (npx-based)
    |--------------------------------------------------------------------------
    | The daemon runs via npx from the package's bundled TypeScript source.
    | Like Vite in Laravel, every project uses package.json + node_modules.
    */
    'daemon' => [
        'manifest_path' => storage_path('app/vurb/manifest.json'),
        'node_path' => env('VURB_NODE_PATH'),
        'npx_path' => env('VURB_NPX_PATH'),
        'port' => env('VURB_DAEMON_PORT'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Bridge Configuration
    |--------------------------------------------------------------------------
    */
    'bridge' => [
        'base_url' => env('VURB_BRIDGE_URL', 'http://127.0.0.1:8000'),
        'prefix' => '/_vurb',
        'timeout' => 30,
    ],

    /*
    |--------------------------------------------------------------------------
    | Global Middleware
    |--------------------------------------------------------------------------
    */
    'middleware' => [
        // \Vinkius\Vurb\Middleware\AuditTrail::class,
        // \Vinkius\Vurb\Middleware\RateLimitVurb::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | State Sync (Epistemic Cache Control)
    |--------------------------------------------------------------------------
    */
    'state_sync' => [
        'default' => 'stale',
        'policies' => [
            // 'geo.*' => ['directive' => 'immutable'],
            // 'billing.*' => ['invalidates' => ['reports.*']],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | FSM State Gate
    |--------------------------------------------------------------------------
    | Set to an array with 'id', 'initial', 'states', 'store' to enable.
    */
    'fsm' => null,

    /*
    |--------------------------------------------------------------------------
    | Introspection & Governance
    |--------------------------------------------------------------------------
    */
    'introspection' => [
        'enabled' => false,
        'filter' => null,
    ],

    /*
    |--------------------------------------------------------------------------
    | DLP Redaction
    |--------------------------------------------------------------------------
    */
    'dlp' => [
        'enabled' => false,
        'patterns' => [],
        'strategy' => 'mask',
    ],

    /*
    |--------------------------------------------------------------------------
    | Observability
    |--------------------------------------------------------------------------
    */
    'observability' => [
        'telescope' => true,
        'pulse' => true,
        'events' => true,
    ],
];
